core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # Django admin
    path('database/', admin.site.urls, name='admin'),
    # User management
    path('accounts/', include('allauth.urls')),
    # Markdownx
    path('markdownx/', include('markdownx.urls')),
    # Local apps
    path('tickets/', include('tickets.urls')),
    path('', include('pages.urls')),
    path('', include('reactions.urls')),
    path('peer-review/', include('review.urls')),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

# Add django-debug-toolbar
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

# Admin site customisation
admin.site.site_header = "neverDrugs.io"
admin.site.site_title = "neverDrugs.io administration"
admin.site.index_title = "neverDrugs.io Admin"

review/urls.py
from django.urls import path

from .views import (
    SessionListView,
    SessionDetailView,
    ReviewListView,
    ReviewDetailView,
    SessionCreateView,
    SessionLatestView,
    SessionEditView,
    ajax_save_review_session,
    ajax_revert_review,
    ajax_auto_update_review,
    ajax_review_detail_view,
    )

urlpatterns = [
    path('', ReviewListView.as_view(), name='review_list'),
    path('<uuid:pk>', ReviewDetailView.as_view(), name='review_detail'),
    path('sessions/', SessionListView.as_view(), name='session_list'),
    path('sessions/<uuid:pk>', SessionDetailView.as_view(), name='session_detail'),
    path('sessions/start', SessionCreateView.as_view(), name='session_create'),
    path('sessions/edit/<uuid:pk>', SessionEditView.as_view(), name='session_edit'),
    path('sessions/latest', SessionLatestView.as_view(), name='session_latest'),
    path('ajax/session', ajax_review_detail_view, name='ajax_review_detail'),
    path('ajax/save', ajax_save_review_session, name='ajax-save-review'),
    path('ajax/revert', ajax_revert_review, name='ajax-revert-review'),
    path('ajax/update', ajax_auto_update_review, name='ajax-update-review'),
    ]

reactions/models.py
import uuid
from datetime import datetime
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.contrib import admin
from django.utils.text import slugify
from django.conf import settings
from django.utils.html import format_html
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify

# Link for Markdown field helptext
markdown_field_helptext = "Add basic formatting using "
markdown_link = "https://www.markdownguide.org/cheat-sheet/"
markdown_link_text = "Markdown (cheat sheet)"
markdown_field_post_helptext = "A live preview of formatted content \
    is shown next to the input field"


class Source(models.Model):
    name = models.CharField(
        max_length=255,
        blank=False,
        verbose_name='Article title')
    publication = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        verbose_name='Journal or publication name')
    reference = models.TextField(
        max_length=2055,
        blank=True,
        null=True,
        verbose_name='Full reference')
    year = models.IntegerField(
        blank=True,
        null=True,
        verbose_name='Year of publication')
    url = models.URLField(
        max_length=255,
        blank=True,
        null=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='source_created_by')
    last_edited_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='source_edited_by')

    def __str__(self):
        return f'{self.name} in {self.publication}'


class DrugClass(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(
        blank=True,
        null=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='drug_class_created_by')
    last_edited_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='drug_class_edited_by')

    def __str__(self):
        return self.name


class Drug(models.Model):
    name = models.CharField(max_length=255, unique=True)
    aliases = models.CharField(
        max_length=1023,
        blank=True,
        null=True)
    slug = models.SlugField(
        null=False,
        unique=True,
        verbose_name='URL title')
    drug_class = models.ManyToManyField(
        DrugClass,
        blank=True,
        related_name='drugs')
    description = MarkdownxField(
        blank=True,
        null=True,
        verbose_name='Description',
        help_text=(
            'Use this field to outline the '
            'drug\'s background and contraindications')
    )
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='drug_created_by')
    last_edited_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='drug_edited_by')

    class Meta:
        ordering = ['name']

    @admin.display(description='Classes')
    def get_drug_classes(self):
        return [drug_class for drug_class in self.drug_class.all()]

    def get_drug_class_string(self):
        return ', '.join(
            [drug_class.name for drug_class in self.drug_class.all()])

    def get_all_interactions(self):
        return self.interactions.all() | self.secondary_drug_interactions.all()

    def get_all_conditions(self):
        return (Condition.objects.filter(
            Q(interactions__drugs=self) | Q(secondary_condition_interactions__drugs=self) | Q(interactions__secondary_drugs=self) | Q(secondary_condition_interactions__secondary_drugs=self))
            .distinct())

    def get_condition_count(self):
        return self.get_all_conditions().count()

    def alias_list(self):
        return self.aliases.split(', ') + [self.name] if self.aliases else [self.name]

    def get_absolute_url(self):
        return reverse('drug_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name


class Condition(models.Model):
    # Peer review choices
    DRAFT = 'DR'
    MODIFY = 'MO'
    MOD_THEN_ACCEPT = 'AM'
    ACCEPT = 'AC'
    peer_review_choices = [
        (DRAFT, 'Draft'),
        (MODIFY, 'Requires modifications, then re-review'),
        (MOD_THEN_ACCEPT, 'Accepted after minor changes'),
        (ACCEPT, 'Accepted'), ]

    # Evidence level choices
    L1 = 'L1'
    L2 = 'L2'
    L3 = 'L3'
    L4 = 'L4'
    L5 = 'L5'
    L6 = 'L6'
    L7 = 'L7'
    evidence_choices = [
        (L1, 'Systematic review of RCTs'),
        (L2, 'Well-designed RCT'),
        (L3, 'Well-designed controlled study without randomisation'),
        (L4, 'Well designed case-control or cohort studies'),
        (L5, 'Reviews of qualitative studies'),
        (L6, 'Single qualitative study'),
        (L7, 'Expert body opinion'), ]

    # TL;DR box choices
    GREY = 'GY'
    BLUE = 'BL'
    YELLOW = 'YE'
    GREEN = 'GN'
    RED = 'RE'
    tldr_box_choices = [
        (GREY, 'Grey'),
        (BLUE, 'Blue'),
        (YELLOW, 'Yellow'),
        (GREEN, 'Green'),
        (RED, 'Red')]

    default_description = (
        '# Overview\n'
        '---\n'
        'Overview text here\n\n'
        '# Pathophysiology\n'
        '---\n'
        'Pathophysiology text here\n\n'
        '# Impacts on anaesthesia\n'
        '---\n'
        'Impacts text here \n\n'
        '### *Drug name here*\n'
        '`Expert opinion` Further detail here')

    name = models.CharField(
        max_length=255,
        unique=True)
    aliases = models.CharField(
        max_length=1023,
        blank=True,
        null=True)
    slug = models.SlugField(
        null=False,
        unique=True,
        verbose_name='URL title')
    tldr = MarkdownxField(
        blank=True,
        null=True,
        verbose_name='TL;DR',
        help_text=(
            'A brief description of the important anaesthetic concern '
            'to appear at the top of the article'))
    tldr_box = models.CharField(
        max_length=2,
        choices=tldr_box_choices,
        default=RED,
        verbose_name='TL;DR banner colour')
    see_also = models.ManyToManyField(
        'self',
        symmetrical=False,
        blank=True,
        verbose_name='See also',
        help_text='Link to related conditions here <br>')
    description = MarkdownxField(
        blank=True,
        null=True,
        default=default_description,
        verbose_name='Article body',
        help_text=format_html(
            '{}<a href="{}" target="_blank" rel="noopener noreferrer">{}</a><br>{}',
            markdown_field_helptext,
            markdown_link,
            markdown_link_text,
            markdown_field_post_helptext))
    sources = models.ManyToManyField(
        Source,
        related_name='condition_sources',
        blank=True)
    evidence = models.CharField(
        max_length=2,
        choices=evidence_choices,
        default=L7)
    ready_for_peer_review = models.BooleanField(
        default=False,
        verbose_name='Ready for peer review?')
    peer_review_status = models.CharField(
        max_length=2,
        choices=peer_review_choices,
        default=DRAFT)
    ready_to_publish = models.BooleanField(
        default=False,
        verbose_name='Ready to publish?')  # False excludes from search
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='condition_created_by')
    last_edited_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='condition_edited_by')

    class Meta:
        ordering = ['name']

    def alias_list(self):
        return self.aliases.split(', ') + [self.name] if self.aliases else [self.name]

    def alias_dict(queryset):
        dict = {}

        def insert_non_duplicates(name, item):
            if name not in dict:
                dict[name] = item
            else:
                dict.pop(name)  # dict should be free of duplicates

        for item in queryset:
            for alias in item.alias_list():
                insert_non_duplicates(alias.lower(), item)
        return dict

    def description_markdown(self):
        # Replace NoneType with '' if empty
        return markdownify(self.description) if self.description else ''

    def tldr_markdown(self):
        # Replace NoneType with '' if empty
        return markdownify(self.tldr) if self.tldr else ''

    def get_tldr_box_colour(self):
        # chooses bootstrap alert colour based on interaction.severity
        alert_dict = {
            'GY': 'alert-secondary',
            'BL': 'alert-primary',
            'YE': 'alert-warning',
            'GN': 'alert-success',
            'RE': 'alert-danger'}
        return alert_dict.get(self.tldr_box) if self.tldr else ''

    def get_absolute_url(self):
        return reverse('condition_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name


class Interaction(models.Model):
    # Severity level choices
    NA = 'NA'
    MILD = 'MI'
    MODERATE = 'MO'
    SEVERE = 'SE'
    severity_choices = [
        (NA, 'Not applicable'),
        (MILD, 'Mild'),
        (MODERATE, 'Moderate'),
        (SEVERE, 'Severe'), ]

review/models.py
import uuid
from django.db import models
from django.conf import settings
from django.urls import reverse
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify

from reactions.models import Condition


class Review(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    condition = models.ForeignKey(
        Condition,
        related_name='Condition',
        on_delete=models.CASCADE)
    comment = MarkdownxField(blank=True, null=True, default='')
    update = MarkdownxField(blank=True, null=True, default='')
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    actioned = models.BooleanField(default=False)

    class Meta:
        ordering = ['-date_created']

    def comment_markdown(self):
        return markdownify(self.comment) if self.comment else ''

    def update_markdown(self):
        return markdownify(self.update) if self.update else ''

    def get_absolute_url(self):
        return reverse("review_detail", kwargs={"pk": self.id})

    def __str__(self):
        name = self.condition.name.capitalize()
        author = self.condition.created_by.username.capitalize()
        return f'\'{name}\' by {author}'


class ReviewSession(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    reviews = models.ManyToManyField(
        Review,
        related_name='reviews',
        verbose_name='Articles for peer review',
        blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    last_ajax = models.DateTimeField(blank=True, null=True)
    open = models.BooleanField(default=False)
    host = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='Chairperson for the meeting',
        null=True,
        blank=True,
        related_name='host')
    user_list = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        verbose_name='Users present during the peer review session',
        blank=True,
        related_name='user_list')

    class Meta:
        ordering = ['-date_created']

    def user_list_string(self):
        users = self.user_list.all()
        return ', '.join(user.username.capitalize() for user in users)

    def get_ajax_url(self):
        return reverse("ajax_review_detail") + f"?id={self.id}"

    def get_absolute_url(self):
        return reverse("session_detail", kwargs={"pk": self.id})

    def __str__(self):
        return f'Review session started {self.date_created}'

review/forms.py
from django import forms
from reactions.models import Condition
from .models import ReviewSession, Review


class InteractionForReviewForm(forms.ModelForm):
    '''
    Filters fields available in the Session CreateView
    '''
    class Meta:
        model = ReviewSession
        fields = ['reviews', 'host', 'open']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['reviews'].queryset = (
            Review.objects  # Exclude accepted articles
            .filter(condition__ready_for_peer_review=True)
            .exclude(condition__peer_review_status='AC')
            .exclude(actioned=True)
            )


class ConditionPeerReviewStatusForm(forms.ModelForm):
    class Meta:
        model = Condition
        fields = ['peer_review_status']
        widgets = {'peer_review_status': forms.Select(attrs={'id': 'selectPeerReviewStatus'})}

templates/review/_review_detail.html
{% extends 'review/_split_view_large.html' %}

{% block left_col %}
<h3 class="display-5 fw-bold">Peer Review</h3>
{% if review_session %}
<a href="{{ review_session.get_absolute_url }}" class="text-decoration-none">&lt; Back to referring session</a>
<div class="row mt-3">
    <div class="col-6">
        <h6>Host:</h6>
        <p>{{review_session.host|capfirst}}</p>
        <span id="connection"></span>
    </div>
    <div class="col-6" id="userList">{% include 'review/fragments/review_users.html' %}</div>
</div>
{% endif %}
<div class="my-3">
    {% block textbox %}{% endblock textbox %}
</div>
{% block buttons %}{% endblock buttons %}
{% endblock left_col %}

{% block right_col %}
<div class="container">
    <div class="p-4 p-md-5 border rounded-3 bg-light row align-items-top d-flex">
        <div class="col-12">
            <div class="pb-3">
                <h1 class="display-5 fw-bold mb-3 text-break">Article: {{ review.condition.name | capfirst }}</h1>
                <small class="text-muted">Author: {{review.condition.created_by|capfirst}}</small><br>
                <small class="text-muted">Last edited by {{review.condition.last_edited_by|capfirst}} on {{ review.condition.date_modified }}</small>
            </div>
            {% for interaction in review.condition.interactions.all %}
            <div class="alert alert-primary px-4 px-md-5" role="alert">
                <h6 class="alert-heading">Strong association with {{interaction.name}}</h6>
                <hr>
                <div class="row">
                    {% if interaction.drugs.all %}
                    <div class="col">
                        <p class="mb-0">Implicated drugs:</p>
                        {% for drug in interaction.drugs.all %}
                        <p class="mb-0 opacity-75">{{drug.name | capfirst}}</p>
                        {% endfor %}
                    </div>
                    {% endif %}
                    {% if interaction.secondary_drugs.all %}
                    <div class="col">
                        <p class="mb-0">Potentially implicated drugs:</p>
                        {% for secondary_drug in interaction.secondary_drugs.all %}
                        <p class="mb-0 opacity-75">{{secondary_drug.name|capfirst}}</p>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
            {% for interaction in review.condition.secondary_condition_interactions.all %}
            <div class="alert alert-secondary px-4 px-md-5" role="alert">
                <h6 class="alert-heading">Potential association with {{interaction.name}}</h6>
                <hr>
                <div class="row">
                    {% if interaction.drugs.all %}
                    <div class="col">
                        <p class="mb-0">Implicated drugs:</p>
                        {% for drug in interaction.drugs.all %}
                        <p class="mb-0 opacity-75">{{drug.name | capfirst}}</p>
                        {% endfor %}
                    </div>
                    {% endif %}
                    {% if interaction.secondary_drugs.all %}
                    <div class="col">
                        <p class="mb-0">Potentially implicated drugs:</p>
                        {% for secondary_drug in interaction.secondary_drugs.all %}
                        <p class="mb-0 opacity-75">{{secondary_drug.name|capfirst}}</p>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col-12">
            {% if review.condition.tldr %}
            <div class="alert {{review.condition.get_tldr_box_colour}} p-3 p-md-5">
                <h3>TL;DR...</h3>
                {{ review.condition.tldr_markdown|safe }}
            </div>
            {% endif %}
            <div class="mb-3 card">
                <div class="card-body p-3 p-md-5">
                    {{ review.condition.description_markdown|safe }}
                </div>
            </div>
            {% if review.condition.sources.all %}
            <button class="btn btn-outline-primary" type="button" data-bs-toggle="collapse"
            data-bs-target="#source-list" aria-expanded="false" aria-controls="source-list">
            View references
        </button>
        <div class="collapse" id="source-list">
            <div class="row">
                {% for source in review.condition.sources.all %}
                <div class="col-12">
                    <div class="card mt-3">
                        <div class="card-body">
                            <h5 class="card-title">{{ source.name }}</h5>
                            <p class="card-text">
                                {{ source.publication }}
                                {% if source.year %}<small
                                class='text-muted'>{{ source.year }}</small>{% endif %}
                            </p>
                            {% if source.url %}<a href="{{source.url}}"
                            class="text-decoration-none">{{ source.url }}</a>{% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock right_col %}

templates/review/_split_view.html
{% extends '_base.html' %}

{% block content %}
<div class="container">
    <div class="row p-4 p-md-2">
        <div class="col-md-6 pt-5 py-md-5">
        {% block left_col %}{% endblock left_col %}
        </div>
        <div class="col-md-6 py-3 py-md-5">
        {% block right_col %}{% endblock right_col %}
        </div>
    </div>
</div>
{% endblock content %}

templates/review/_split_view_large.html
{% extends '_base.html' %}

{% block content %}
<div class="container">
    <div class="row p-4 p-md-2">
        <div class="col-md-4 pt-5 py-md-5">
        {% block left_col %}{% endblock left_col %}
        </div>
        <div class="col-md-8 py-3 py-md-5">
        {% block right_col %}{% endblock right_col %}
        </div>
    </div>
</div>
{% endblock content %}

templates/review/review_detail.html
{% extends 'review/_review_detail.html' %}
{% load static %}

{% block textbox %}
<div class="card">
    <div class="card-body" id="reviewCommentTextarea">
        {% if review.update_markdown %}
        {{ review.update_markdown | safe}}
        {% else %}
        <div class="text-muted">Peer review meeting comments will appear in this space</div>
        {% endif %}
    </div>
</div>
<div class="pt-3">
<span class="h6">Peer review status: </span><span id="textPeerReview">{{review.condition.get_peer_review_status_display}}</span></p>
</div>
{% endblock textbox %}

{% block javascript %}
<script>
const update_url = "{% url 'ajax-update-review' %}?review_id={{ review.id }}{% if review_session %}&session_id={{ review_session.id }}{% endif %}";</script>
<script src="{% static 'js/review_detail.js' %}"></script>
{% endblock javascript %}

templates/review/review_host_detail.html
{% extends 'review/_review_detail.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block textbox %}
<textarea class="form-control" placeholder="Meeting comments for this article" rows="10" id="reviewTextarea">{{ review.comment }}</textarea>
{% endblock textbox %}

{% block buttons %}
{{ peer_review_form|crispy }}
<div class="btn-group d-flex pb-5 pb-md-0" role="group" aria-label="Article comment buttons">
    <button class="btn btn-outline-primary" id="btnSave">Save changes</button>
    <button class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#confirmRevert">Revert</button>
</div>

<div class="modal fade" id="confirmRevert" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="confirmRevertLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="confirmRevertLabel">Are you sure you want to revert changes?</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <p>Comment will be reverted to:</p>
          <div id="revertComment">{{review.comment|linebreaks}}</div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-danger" id="btnRevert">Revert</button>
        </div>
      </div>
    </div>
  </div>
{% endblock buttons %}

{% block javascript %}
<script>
const review_id = "{{review.id}}";
const session_id = "{{review_session.id}}";
const save_url = "{% url 'ajax-save-review' %}";
const revert_url = "{% url 'ajax-revert-review' %}";
const update_url = "{% url 'ajax-update-review' %}";
const get_param = "?review_id={{ review.id }}&session_id={{ review_session.id }}"
</script>
<script src="{% static 'js/review_host_detail.js' %}"></script>
{% endblock javascript %}

templates/review/reviewsession_create.html
{% extends 'review/_split_view_large.html' %}
{% load crispy_forms_tags %}

{% block left_col %}
<h1 class="display-5 fw-bold lh-1 mb-3 text-break">Start a new meeting</h1>
<p class="lead">Select interactions to peer-review during this meeting</p>
{% endblock left_col %}

{% block right_col %}
<form method="post">{% csrf_token %}
    {{ form | crispy }}
    <input type="submit" class="btn btn-outline-primary" value="Start meeting">
</form>
{% endblock right_col %}

templates/review/session_create.html
{% extends 'review/_split_view_large.html' %}
{% load crispy_forms_tags %}

{% block left_col %}
<h1 class="display-5 fw-bold lh-1 mb-3 text-break">Start a new meeting</h1>
<p class="lead">Select conditions to peer-review during this meeting</p>
{% endblock left_col %}

{% block right_col %}
<form method="post">{% csrf_token %}
    {{ form | crispy }}
    <input type="submit" class="btn btn-outline-primary" value="Start meeting">
</form>
{% endblock right_col %}

templates/review/session_detail.html
{% extends 'review/_split_view_large.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/reviews.css' %}">
{% endblock css %}

{% block left_col %}
<h1 class="fw-bold lh-1 mb-3">Articles Under Review</h1>
<a href="{% url 'session_list' %}" class="text-decoration-none">&lt; Back to all meetings</a>
<div class="list-group pt-3">
    {% for review in reviews %}
    <button class="review-button list-group-item list-group-item-action {% if forloop.first %}active{% endif %}" type="button" id="{{review.id}}">
        <h5 class="mb-1">{{ review.condition.name }}</h5>
        <small>{{ review.date_created }}</small>
    </button>
    {% endfor %}
</div>
{% endblock left_col %}

{% block right_col %}
<div class="alert alert-primary" role="alert">
    <h4 class="alert-heading">Peer review notes</h4>
    <p>The following articles have been selected for peer review in this session. Notes from the peer review are displayed below.</p>
    <hr>
    <p class="mb-0">Join the article discussion to view real-time changes</p>
  </div>
{% for review in reviews %}
<div class="review{% if not forloop.first %} hide{%endif%}" id="review-{{review.id}}">
    <div class="card">
            <h5 class="card-header">{{ review.condition.name }}</h5>
        <div class="card-body">
            <h5 class="card-title">Article status: {{review.condition.get_peer_review_status_display|lower}}</h5>
            <p>
                <span class="card-text">Author: {{ review.condition.created_by|capfirst }}<br></span>
                <span class="card-text">Last modified by: {{ review.condition.last_edited_by|capfirst }}<br></span>
            </p>
            <p class="text-muted small">{{ review.date_created }}</p>
            <a href="{{review.get_absolute_url}}?session_id={{session.id}}" class="btn btn-outline-primary">Join Real-Time Discussion</a>
            {% if review.comment %}
            <hr>
            <h5 class="card-title">Review notes:</h5>
            <p class="card-text">{{ review.comment_markdown|safe }}</p>
            {% endif %}
            
        </div>
    </div>
</div>
{% endfor %}
{% endblock right_col %}

{% block javascript %}
<script src="{% static 'js/review_list.js' %}"></script>
{% endblock javascript %}

templates/review/session_edit.html
{% extends 'review/_split_view_large.html' %}
{% load crispy_forms_tags %}

{% block left_col %}
<form method="post">{% csrf_token %}
    {{ form | crispy }}
    <input type="submit" class="btn btn-outline-primary" value="Start meeting">
</form>

{% endblock left_col %}

{% block right_col %}{% endblock right_col %}

templates/review/session_list.html
{% extends 'review/_split_view.html' %}
{% load static %}

{% block left_col %}
<h1 class="fw-bold lh-1 mb-3 pb-2">Peer Review Meetings</h1>
<div class="list-group">
{% for session in session_list %}
<a href="{{ session.get_absolute_url }}" class="{% if forloop.first %}active {% endif %}list-group-item list-group-item-action review_link" ajax="{{ session.get_ajax_url }}">
    <div class="row justify-content-between">
        <div class="col-8">
        <h5 class="mb-1">Meeting on {{ session.date_created | date:"l j/n/Y" }}</h5>
        </div>
        {% if session.open or session.reviews.all %}
        <div class="col-4 text-end">
        {% if session.open %}
        <span class="badge bg-danger rounded-pill">Live</span>
        {% endif %}
        {% if session.reviews.all %}
        <span class="badge bg-dark rounded-pill ms-1">
            {{ session.reviews.all.count }} Article{{ session.reviews.all.count|pluralize }}
        </span>
        {% endif %}
        </div>
        {% endif %}
    </div>
    {% if session.host %}
    <p class="mb-1">Session host: {{ session.host.username|capfirst }}</p>
    {% endif %}
    {% if session.user_list.all %}
        <small>Participant{{ session.user_list.all|pluralize }}: {{ session.user_list_string }}</small>
    {% endif %}
</a>
{% endfor %}
</div>
{% endblock left_col %}

{% block right_col %}
<div class="pt-2 pt-md-3" id="display-pane">
    {% with session_list|first as session %}
    {% with session.reviews.all as review_list%}
    {% include 'review/fragments/review_preview.html' %}
    {% endwith %}
    {% endwith %}
</div>
{% endblock right_col %}

{% block javascript %}
<script src='{% static 'js/session.js' %}'></script>
{% endblock javascript %}